StartingLine_RivalHouse_2F_MapScripts::
	.byte 0

StartingLine_RivalHouse_2F_EventScript_GamecubeOne::
    msgbox StartingLine_RivalHouse_2F_Text_GamecubeOne, MSGBOX_SIGN
    end

StartingLine_RivalHouse_2F_Text_GamecubeOne:
    .string "No way...$"

StartingLine_RivalHouse_2F_EventScript_GamecubeTwo::
    msgbox StartingLine_RivalHouse_2F_Text_GamecubeTwo, MSGBOX_SIGN
    end

StartingLine_RivalHouse_2F_Text_GamecubeTwo:
    .string "She has...$"

StartingLine_RivalHouse_2F_EventScript_GamecubeThree::
    msgbox StartingLine_RivalHouse_2F_Text_GamecubeThree, MSGBOX_SIGN
    end

StartingLine_RivalHouse_2F_Text_GamecubeThree:
    .string "THREE GAMECUBES!?$"

StartingLine_RivalHouse_2F_EventScript_Notebook::
    msgbox StartingLine_RivalHouse_2F_Text_Notebook, MSGBOX_SIGN
    end

StartingLine_RivalHouse_2F_Text_Notebook:
    .string "Finally. Today's the day I go on a\n"
    .string "Pokemon adventure. I sure hope I don't\l"
    .string "run into my loser neighbor, {PLAYER}.$"
